#!/usr/bin/env bash
set -u

# Set AMGX, PCG_V, and AMG_CG to files in an AMGX installation.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
ROOT=$(cd -- "$SCRIPT_DIR/.." && pwd)
AMGX=${AMGX:-amgx_capi}
PCG_V=${PCG_V:-PCG_V.json}
AMG_CG=${AMG_CG:-AMG_CLASSICAL_CG.json}
DATA=${DATA:-$ROOT/data/amgx}

# Graph Laplacians
printf '\n%.0s' {1..30}
$AMGX -m $DATA/com-LiveJournal.mtx -c $PCG_V
printf '\n%.0s' {1..30}
$AMGX -m $DATA/GAP-road.mtx -c $AMG_CG
printf '\n%.0s' {1..30}
$AMGX -m $DATA/europe_osm.mtx -c $AMG_CG
printf '\n%.0s' {1..30}
$AMGX -m $DATA/delaunay_n24.mtx -c $AMG_CG
printf '\n%.0s' {1..30}
$AMGX -m $DATA/venturiLevel3.mtx -c $PCG_V
printf '\n%.0s' {1..30}
$AMGX -m $DATA/belgium_osm.mtx -c $AMG_CG

# Physics matrices
printf '\n%.0s' {1..30}
$AMGX -m $DATA/parabolic_fem.mtx -c $PCG_V
printf '\n%.0s' {1..30}
$AMGX -m $DATA/ecology1.mtx -c $AMG_CG
printf '\n%.0s' {1..30}
$AMGX -m $DATA/ecology2.mtx -c $PCG_V
printf '\n%.0s' {1..30}
$AMGX -m $DATA/apache2.mtx -c $PCG_V
printf '\n%.0s' {1..30}
$AMGX -m $DATA/G3_circuit.mtx -c $PCG_V
printf '\n%.0s' {1..30}
$AMGX -m $DATA/spe16m.mtx -c $PCG_V
printf '\n%.0s' {1..30}
$AMGX -m $DATA/uniform_3D.mtx -c $PCG_V
printf '\n%.0s' {1..30}
$AMGX -m $DATA/aniso_contrast_3D.mtx -c $PCG_V
printf '\n%.0s' {1..30}
$AMGX -m $DATA/poisson_contrast_3D.mtx -c $PCG_V
printf '\n%.0s' {1..30}
